[profile.default]
    src = "src"
    out = "out"
    libs = ["lib"]
    auto_detect_solc = false
    block_timestamp = 1_680_220_800 # March 31, 2023 at 00:00 GMT
    bytecode_hash = "ipfs"
    evm_version = "cancun"
    fuzz = { runs = 1_000 }
    via-ir = false
    gas_reports = ["*"]
    optimizer = true
    optimizer_runs = 1_000_000
    script = "scripts"
    solc = "0.8.26"
    test = "test"
    cache_path  = "cache_forge"
    gas_reports_ignore = ["MockToken"]
    remappings = [
        "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
        "ds-test/=lib/forge-std/lib/ds-test/src/",
        "erc4626-tests/=lib/forge-std/lib/erc4626-tests/",
        "forge-std/=lib/forge-std/src/",
        "openzeppelin-contracts/=lib/openzeppelin-contracts/",
        "v3-core/=lib/v3-core/",
        "v3-periphery/=lib/v3-periphery/contracts/",
        "@uniswap/v3-core/=lib/v3-core/",
        "@uniswap/swap-router/=lib/swap-router-contracts/"
    ]

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 150
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[etherscan]
  baseSepolia = { key = "${API_KEY_BASESCAN}" }
  base = { key = "${API_KEY_BASESCAN}" }

[rpc_endpoints]
  baseSepolia = "https://sepolia.base.org"
  base = "https://1rpc.io/base"
  local = "http://localhost:8545"
